[theme]
font="serif"


[server]
port = 8080
enableCORS=false
enableXsrfProtection=false

[client]
# Controls whether uncaught app exceptions are displayed in the browser. By default, this is set to True and Streamlit displays app exceptions and associated tracebacks in the browser.
# If set to False, an exception will result in a generic message being shown in the browser, and exceptions and tracebacks will be printed to the console only.
# Default: true
showErrorDetails = false

[browser]
gatherUsageStats = false
serverAddress = "10.208.6.150"

[ui]
# Flag to hide most of the UI elements found at the top of a Streamlit app.
# NOTE: This does *not* hide the hamburger menu in the top-right of an app.
# Default: false
hideTopBar = true

