[theme]
font="sans serif"

[server]
port = 8080
enableCORS=false
enableXsrfProtection=false

[browser]
gatherUsageStats = false
serverAddress = "10.208.6.150"

[ui]
# Flag to hide most of the UI elements found at the top of a Streamlit app.
# NOTE: This does *not* hide the hamburger menu in the top-right of an app.
# Default: false
hideTopBar = true